# Generated by Django 2.2.5 on 2019-09-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etnia',
            name='descricao',
            field=models.CharField(max_length=30, unique=True, verbose_name='Descrição'),
        ),
    ]
